/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSplatRouteImport } from './routes/product/$'
import { Route as ApiAuthTokenRouteImport } from './routes/api/auth-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSplatRoute = ProductSplatRouteImport.update({
  id: '/product/$',
  path: '/product/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokenRoute = ApiAuthTokenRouteImport.update({
  id: '/api/auth-token',
  path: '/api/auth-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth-token': typeof ApiAuthTokenRoute
  '/product/$': typeof ProductSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth-token': typeof ApiAuthTokenRoute
  '/product/$': typeof ProductSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth-token': typeof ApiAuthTokenRoute
  '/product/$': typeof ProductSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth-token' | '/product/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth-token' | '/product/$'
  id: '__root__' | '/' | '/api/auth-token' | '/product/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthTokenRoute: typeof ApiAuthTokenRoute
  ProductSplatRoute: typeof ProductSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$': {
      id: '/product/$'
      path: '/product/$'
      fullPath: '/product/$'
      preLoaderRoute: typeof ProductSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-token': {
      id: '/api/auth-token'
      path: '/api/auth-token'
      fullPath: '/api/auth-token'
      preLoaderRoute: typeof ApiAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthTokenRoute: ApiAuthTokenRoute,
  ProductSplatRoute: ProductSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
